iou_threshold: 0.1
score_threshold: 0.1
# Maximum number of frames to keep alive a track without associated detections.
max_age: 10
# Minimum number of associated detections before track is initialised
min_hits: 1
