#!/bin/bash

#SBATCH -p gpu # partition
#SBATCH -N 1   # number of nodes
#SBATCH --mem 12G # memory pool for all cores
#SBATCH -n 2 # number of cores
#SBATCH -t 3-04:00 # time (D-HH:MM)
#SBATCH --gres gpu:1 # request 1 GPU (of any kind)
#SBATCH -o slurm.%N.%j.out # write STDOUT
#SBATCH -e slurm.%N.%j.err # write STDERR
#SBATCH --mail-type=ALL
#SBATCH --mail-user=s.minano@ucl.ac.uk

# Load the SLEAP module
module load SLEAP

# Define directories for data and exported training job
# TODO: have this as a CLI argument?
MODEL_DIR=/ceph/zoo/users/sminano/crabs_pose_4k_TD4
TRAINING_JOB_DIR=$MODEL_DIR/labels.v001.slp.training_job

# Go to the training job directory
cd $TRAINING_JOB_DIR

# Run the training script generated by SLEAP
./train-script.sh
