num_epochs: 250
learning_rate: 0.00005
wdecay: 0.00005
batch_size_train: 2
batch_size_test: 1
batch_size_val: 1
num_classes: 2
save: True
train_fraction: 0.5
val_over_test_fraction: 0.5
iou_threshold: 0.1
num_workers: 4
transform_brightness: 0.5
transform_hue: 0.3
gaussian_blur_params:
  kernel_size:
    - 5
    - 9
  sigma:
    - 0.1
    - 5.0
optuna_param:
  n_trials:
    - 5
  learning_rate:
    - 1e-6
    - 1e-4
  num_epochs:
    - 100
    - 300
exclude_video_file_list:
  - "06.09.2023-03-Right_RE_frame_181451.png"
