n_epochs: 250
learning_rate: 0.00005
wdecay: 0.00005
batch_size_train: 4
batch_size_test: 4
batch_size_val: 4
num_classes: 2
train_fraction: 0.8
val_over_test_fraction: 0.5
checkpoint_saving:
  every_n_epochs: 50
  keep_last_n_ckpts: 5
  save_weights_only: True
  copy_as_mlflow_artifacts: True
  # copy_as_mlflow_artifacts:
  # if True, selected checkpoints are added as artifacts at the end of training,
  # if all, all checkpoints for every epoch are added as artifacts during training,
  # if False, no checkpoints are added as artifacts.
  save_last: True
iou_threshold: 0.1
num_workers: 4
transform_brightness: 0.5
transform_hue: 0.3
gaussian_blur_params:
  kernel_size:
    - 5
    - 9
  sigma:
    - 0.1
    - 5.0
# when we run Optuna, the n_trials and n_epochs above will be overwrite by the parameters set by Optuna
optuna:
  # The number of trials to determines how many different combinations Optuna will try.
  n_trials: 3
  # The lower bound and the upper bound of the learning rate parameter
  learning_rate:
    - 1e-6
    - 1e-4
  # The lower bound and the upper bound of the number of epochs
  n_epochs:
    - 1
    - 3
