num_epochs: 1
learning_rate: 0.00005
wdecay: 0.00005
batch_size_train: 4
batch_size_test: 4
batch_size_val: 4
num_classes: 2
train_fraction: 0.8
val_over_test_fraction: 0.5
checkpoint_saving:
  every_n_epochs: 50
  keep_last_n_ckpts: 5
  save_weights_only: False
  copy_as_mlflow_artifacts: True
  # copy_as_mlflow_artifacts:
  # if True, selected checkpoints are added as artifacts at the end of training,
  # if all, all checkpoints for every epoch are added as artifacts during training,
  # if False, no checkpoints are added as artifacts.
  save_last: True
iou_threshold: 0.1
num_workers: 4
transform_brightness: 0.5
transform_hue: 0.3
gaussian_blur_params:
  kernel_size:
    - 5
    - 9
  sigma:
    - 0.1
    - 5.0
optuna:
  # Parameters for hyperparameter optimisation with Optuna:
  # - We can optimize `learning_rate`, `num_epochs` or both
  # - n_trials defines the total number of trials ran in the optimisation
  n_trials: 2
  learning_rate:
    - 1e-6
    - 1e-4
