num_epochs: 4
learning_rate: 0.00005
wdecay: 0.00005
batch_size_train: 4
batch_size_test: 1
batch_size_val: 1
num_classes: 2
train_fraction: 0.8
val_over_test_fraction: 0.1
iou_threshold: 0.1
num_workers: 7
num_workers_val: 7
transform_brightness: 0.5
transform_hue: 0.3
gaussian_blur_params:
  kernel_size:
    - 5
    - 9
  sigma:
    - 0.1
    - 5.0
optuna_param:
  n_trials:
    - 3
  learning_rate:
    - 1e-6
    - 1e-4
  num_epochs:
    - 1
    - 2
exclude_video_file_list:
  - "06.09.2023-03-Right_RE_frame_181451.png"
