num_epochs: 250
learning_rate: 0.00005
wdecay: 0.00005
batch_size_train: 4
batch_size_test: 1
num_classes: 2
save: True
train_fraction: 0.8
val_over_test_fraction: 0
num_workers: 7
transform_brightness: 0.5
transform_hue: 0.3
gaussian_blur_params:
  kernel_size:
    - 5
    - 9
  sigma:
    - 0.1
    - 5.0
exclude_video_file_list:
  - "06.09.2023-03-Right_RE_frame_181451.png"
