num_epochs: 4
learning_rate: 0.00005
wdecay: 0.00005
batch_size_train: 1
batch_size_test: 1
batch_size_val: 1
num_classes: 2
train_fraction: 0.8
val_over_test_fraction: 0.5
checkpoint_saving:
  every_n_epochs: 1
  keep_last_n_ckpts: 2
  save_weights_only: True
  copy_as_mlflow_artifacts: True
  save_last: True
iou_threshold: 0.1
num_workers: 0
transform_brightness: 0.5
transform_hue: 0.3
gaussian_blur_params:
  kernel_size:
    - 5
    - 9
  sigma:
    - 0.1
    - 5.0
